server:
  port: 9411
spring:
  application:
    name: zipkin-storage-server
  datasource:
    schema: classpath:/zipkin.sql
    url: jdbc:mysql://localhost:3306/zipkin??characterEncoding=utf-8&useUnicode=true
    username: cmsdemo
    password: cmsdemo@123
    driver-class-name: com.mysql.jdbc.Driver
    initialize: true
    continue-on-error: true
  sleuth:
    enabled: false
    sampler:
      percentage: 1.0
zipkin:
  storage:
    type: mysql