server:
  port: 1119
spring:
  application:
    name: ribbon-hystrix-eureka-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
  instance:
    prefer-ip-address: true
ribbon:
  eureka:
    enabled: true
feign:
  hystrix:
    enabled: true